// Mocks generated by Mockito 5.4.4 from annotations
// in cinema_mate/test/application/cinema/movie_watcher_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cinema_mate/domain/crudMovie/update_movie/update_failure.dart'
    as _i8;
import 'package:cinema_mate/domain/movie/i_movieRepository.dart' as _i3;
import 'package:cinema_mate/domain/movie/movie.dart' as _i7;
import 'package:cinema_mate/domain/movie/movieFailure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:kt_dart/kt.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IMovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMovieRepository extends _i1.Mock implements _i3.IMovieRepository {
  MockIMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.MovieFailure, _i6.KtList<_i7.MovieInfo>>>
      watchAll() => (super.noSuchMethod(
            Invocation.method(
              #watchAll,
              [],
            ),
            returnValue: _i4.Stream<
                _i2
                .Either<_i5.MovieFailure, _i6.KtList<_i7.MovieInfo>>>.empty(),
          ) as _i4
              .Stream<_i2.Either<_i5.MovieFailure, _i6.KtList<_i7.MovieInfo>>>);

  @override
  _i4.Future<_i2.Either<_i8.UpdateFailure, _i2.Unit>> editMovie(
          _i7.EditMovie? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #editMovie,
          [movie],
        ),
        returnValue: _i4.Future<_i2.Either<_i8.UpdateFailure, _i2.Unit>>.value(
            _FakeEither_0<_i8.UpdateFailure, _i2.Unit>(
          this,
          Invocation.method(
            #editMovie,
            [movie],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i8.UpdateFailure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.MovieFailure, _i2.Unit>> deleteMovie(
          _i7.MovieInfo? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMovie,
          [movie],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.MovieFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.MovieFailure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteMovie,
            [movie],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.MovieFailure, _i2.Unit>>);
}
